### ISSUE TITLE
FzfPreviewProjectGrep issues

### ISSUE THREAD

**Issue by kristijanhusak** [yuki-yano/fzf-preview.vim#18]
Hi,

I found few issues with FzfPreviewProjectGrep:

1. It requires `ruby`. It's not noted in the requirements.
2. It requires `bat` or `ccat` (check screenshot)
3. It requires `gsed`, which i don't have on Manjaro i3, and can't find it in aur.

![screenshot](https://i.imgur.com/vkhWl1R.png)

**Comment by yuki-yano** [comment]
2 and 3 have been modified.
Please check.

Later, the dependency of ruby is described in README and doc.

**Comment by elentok** [comment]
Thanks for the quick response 👍 

The "gsed" issue has been fixed, but when selecting a file it doesn't seem to open it:

![image](https://user-images.githubusercontent.com/1129276/74021080-91a18500-49a3-11ea-8cbd-585fb47dd4b0.png)

![image](https://user-images.githubusercontent.com/1129276/74021142-b8f85200-49a3-11ea-9353-194891b4f27a.png)

It seems to be an issue with the result parsing, it tries to try to open `framework:11:source /home/david/.dotfiles/zsh/core.sh`

**Comment by kristijanhusak** [comment]
Preview is shown now, but it still shows `which` errors.

![screenshot](https://i.imgur.com/w9qIz7c.png)

And I have the same problem as @elentok, it won't open.

**Comment by yuki-yano** [comment]
[file-line](https://github.com/bogado/file-line) plugin is required to open files with FzfPreviewProjectGrep. Ref: #2
https://github.com/yuki-ycino/fzf-preview.vim/blob/master/doc/fzf_preview_vim.txt#L42-L44

In my environment, which error was not displayed, so check again.

The preview script will be migrated to Python in the future.

**Comment by kristijanhusak** [comment]
Still showing 'which' errors even after update. Same as screenshot above.
Also FzfPreviewGitFiles is not opening file, because it opens it with git flag (For example, instead of opening init.vim, it tries to open `M init.vim`)

**Comment by yuki-yano** [comment]
which error message was fixed by 3ef27d317bae707bae3cb0fd272918f3318f2d00
Thanks @yutakatay

The bug of FzfPreviewGitFiles (FzfPreviewGitStatus?) has been confirmed.

**Comment by yuki-yano** [comment]
Fixed by d52179060b498805d34730911927175768f3de5a

**Comment by yuki-yano** [comment]
Added that Ruby is required 6f3611f75d2c1b8d14df49395be53351726ae01d

**Comment by yuki-yano** [comment]
Removed dependency on file-line plugin

**Comment by kristijanhusak** [comment]
@yuki-ycino After code was switched to Python, i have similar issues like before. Here's the screenshot:
![screenshot](https://i.imgur.com/lLFOXfG.png)

I don't really want to use bat or ccat because i don't need coloring. Also i know `gsed` part also checked for `sed`, but looks like that's not the case any more.

**Comment by yuki-yano** [comment]
Sorry for degradation
Fix bd1eae3

If processing is unnecessary, consider creating a preview script and setting it to `g:fzf_preview_grep_preview_cmd`.
The problem should be less likely if the format of the command used for grep is not changed.

**Comment by kristijanhusak** [comment]
@yuki-ycino everything works great now. Thanks!
